### ISSUE TITLE
Crash when dragging on minimap

### ISSUE THREAD

**Issue by squiddy** [unknown-horizons/unknown-horizons#2549]
As reported by @fraang (https://github.com/unknown-horizons/unknown-horizons/commit/70de4b30a9065522b783e06d51399b297eb0105c#commitcomment-19626738)

Introduced by 70de4b30a9065522b783e06d51399b297eb0105c

**Steps to reproduce:**

1. Start a game
2. Start dragging the mouse on the minimap
```
AL lib: (WW) FreeDevice: (0x330f900) Deleting 2 Buffer(s)
Traceback (most recent call last):
 File "/usr/lib/python2.7/dist-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
 File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/dist-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(*args,**kwargs)
 File "/home/xxx/unknown-horizons/horizons/gui/widgets/minimap.py", line 392, in _on_drag
    self.on_click(event, drag=True)
AttributeError: 'Minimap' object has no attribute 'on_click'

Traceback (most recent call last):
  File "./run_uh.py", line 382, in <module>
    main()
  File "./run_uh.py", line 191, in main
    ret = horizons.main.start(options)
  File "/home/xxx/unknown-horizons/horizons/main.py", line 246, in start
    horizons.globals.fife.run()
  File "/home/xxx/unknown-horizons/horizons/engine/engine.py", line 278, in run
    self.loop()
  File "/home/xxx/unknown-horizons/horizons/engine/engine.py", line 285, in loop
    self.engine.pump()
  File "/usr/lib/python2.7/dist-packages/fife/fife.py", line 2716, in pump
    return _fife.Engine_pump(self)
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed
```
